from pathlib import Path


def replace_once(path: str, old: str, new: str, label: str) -> None:
    p = Path(path)
    text = p.read_text(encoding="utf-8")
    if new in text:
        return
    if old not in text:
        raise RuntimeError(f"{label}: source block not found in {path}")
    p.write_text(text.replace(old, new, 1), encoding="utf-8")

KEYBOARDS = "mafia_optimisma/keyboards.py"
CALLBACKS = "mafia_optimisma/routers_callbacks.py"
ENGINE = "mafia_optimisma/engine.py"
MODELS = "mafia_optimisma/models.py"

replace_once(KEYBOARDS, '''def verdict_keyboard(game: GameState) -> InlineKeyboardMarkup:\n    return InlineKeyboardMarkup(inline_keyboard=[[\n        InlineKeyboardButton(\n            text="👍 Казнить",\n            callback_data=f"verdict:{game.session_id}:{game.chat_id}:{game.day}:yes",\n        ),\n        InlineKeyboardButton(\n            text="👎 Помиловать",\n            callback_data=f"verdict:{game.session_id}:{game.chat_id}:{game.day}:no",\n        ),\n    ]])\n''', '''def verdict_keyboard(game: GameState) -> InlineKeyboardMarkup:\n    return InlineKeyboardMarkup(inline_keyboard=[\n        [\n            InlineKeyboardButton(\n                text="👍 Казнить",\n                callback_data=f"verdict:{game.session_id}:{game.chat_id}:{game.day}:yes",\n            ),\n            InlineKeyboardButton(\n                text="👎 Помиловать",\n                callback_data=f"verdict:{game.session_id}:{game.chat_id}:{game.day}:no",\n            ),\n        ],\n        [InlineKeyboardButton(\n            text="🤍 Воздержаться",\n            callback_data=f"verdict:{game.session_id}:{game.chat_id}:{game.day}:abstain",\n        )],\n    ])\n''', "add abstain verdict button")

replace_once(CALLBACKS, '''        if voter.user_id in game.verdict_votes:\n            await callback.answer("Твой голос уже принят.", show_alert=True)\n            return\n        if value not in {"yes", "no"}:\n            await callback.answer("Неизвестный вариант.", show_alert=True)\n            return\n        game.verdict_votes[voter.user_id] = value == "yes"\n        await engine.persist(game)\n\n    await callback.answer("👍 За казнь" if value == "yes" else "👎 За помилование")\n''', '''        if value not in {"yes", "no", "abstain"}:\n            await callback.answer("Неизвестный вариант.", show_alert=True)\n            return\n        had_previous = voter.user_id in game.verdict_votes\n        previous = game.verdict_votes.get(voter.user_id)\n        current = {"yes": True, "no": False, "abstain": None}[value]\n        game.verdict_votes[voter.user_id] = current\n        await engine.persist(game)\n\n    label = {"yes": "👍 Казнить", "no": "👎 Помиловать", "abstain": "🤍 Воздержаться"}[value]\n    if had_previous and previous != current:\n        await callback.answer(f"Решение изменено: {label}")\n    elif had_previous:\n        await callback.answer(f"Твой выбор уже: {label}")\n    else:\n        await callback.answer(f"Выбор принят: {label}")\n''', "allow changing verdict choice")

replace_once(MODELS, '''    # Stage 2 voting: voter -> True (execute) / False (pardon).\n    verdict_votes: dict[int, bool] = field(default_factory=dict)\n''', '''    # Stage 2 voting: voter -> True (execute) / False (pardon) / None (abstain).\n    # Missing key means the player has not voted at all.\n    verdict_votes: dict[int, bool | None] = field(default_factory=dict)\n''', "verdict vote model supports abstain")
replace_once(MODELS, '''        game.verdict_votes = {\n            int(uid): bool(value)\n            for uid, value in (data.get("verdict_votes") or {}).items()\n        }\n''', '''        game.verdict_votes = {\n            int(uid): (None if value is None else bool(value))\n            for uid, value in (data.get("verdict_votes") or {}).items()\n        }\n''', "preserve abstain on restore")

replace_once(ENGINE, '''                    f"До конца решения — {self._seconds_text(verdict_seconds)} секунд.\\n\\n"\n                    "👍 Казнить или 👎 Помиловать?",\n''', '''                    f"До конца решения — {self._seconds_text(verdict_seconds)} секунд.\\n\\n"\n                    "👍 Казнить · 👎 Помиловать · 🤍 Воздержаться\\n"\n                    "<i>Решение можно менять до конца таймера — учитывается последний выбор.</i>",\n''', "explain mutable verdict")
replace_once(ENGINE, '''            yes_voters = [uid for uid, value in game.verdict_votes.items() if value]\n            no_voters = [uid for uid, value in game.verdict_votes.items() if not value]\n            yes_names = "\\n".join(f"• {player_link(game.get_player(uid))}" for uid in yes_voters if game.get_player(uid)) or "• —"\n            no_names = "\\n".join(f"• {player_link(game.get_player(uid))}" for uid in no_voters if game.get_player(uid)) or "• —"\n            await self._safe_group(\n                bot,\n                game.chat_id,\n                "⚖️ <b>Вердикт города</b>\\n"\n                "━━━━━━━━━━━━\\n"\n                f"👍 <b>За казнь — {len(yes_voters)}</b>\\n{yes_names}\\n\\n"\n                f"👎 <b>За помилование — {len(no_voters)}</b>\\n{no_names}",\n            )\n''', '''            yes_voters = [uid for uid, value in game.verdict_votes.items() if value is True]\n            no_voters = [uid for uid, value in game.verdict_votes.items() if value is False]\n            abstain_voters = [uid for uid, value in game.verdict_votes.items() if value is None]\n            yes_names = "\\n".join(f"• {player_link(game.get_player(uid))}" for uid in yes_voters if game.get_player(uid)) or "• —"\n            no_names = "\\n".join(f"• {player_link(game.get_player(uid))}" for uid in no_voters if game.get_player(uid)) or "• —"\n            abstain_names = "\\n".join(f"• {player_link(game.get_player(uid))}" for uid in abstain_voters if game.get_player(uid)) or "• —"\n            await self._safe_group(\n                bot,\n                game.chat_id,\n                "⚖️ <b>Вердикт города</b>\\n"\n                "━━━━━━━━━━━━\\n"\n                f"👍 <b>За казнь — {len(yes_voters)}</b>\\n{yes_names}\\n\\n"\n                f"👎 <b>За помилование — {len(no_voters)}</b>\\n{no_names}\\n\\n"\n                f"🤍 <b>Воздержались — {len(abstain_voters)}</b>\\n{abstain_names}",\n            )\n''', "count explicit abstentions separately")

print("MUTABLE VERDICT HOTFIX APPLIED")
