from pathlib import Path

ENGINE = Path("mafia_optimisma/engine.py")
CALLBACKS = Path("mafia_optimisma/routers_callbacks.py")
PRIVATE = Path("mafia_optimisma/routers_private.py")


def replace_once(path: Path, old: str, new: str, label: str) -> None:
    text = path.read_text(encoding="utf-8")
    if new in text:
        return
    if old not in text:
        raise RuntimeError(f"{label}: source block not found in {path}")
    path.write_text(text.replace(old, new, 1), encoding="utf-8")


replace_once(
    ENGINE,
    '''        if game.players:\n            for p in sorted(game.players.values(), key=lambda x: (x.number or 10**9, x.user_id)):\n                tag = f"@{p.username}" if p.username else escape(p.name)\n                lines.append(f"{p.number}) {tag}")\n        else:\n            lines.append("— пока никого")\n        lines += [\n            "",\n            f"👤 Всего: <b>{len(game.players)}</b>",\n            f"Минимум для старта: <b>{MODES[game.mode]['min_players']}</b>",\n            "",\n            "Нажми кнопку ниже, чтобы войти в игру.",\n        ]\n''',
    '''        pending_activation = {\n            int(uid) for uid in (game.temp.get("_pending_pm_activation") or [])\n            if str(uid).lstrip("-").isdigit()\n        }\n        if game.players:\n            for p in sorted(game.players.values(), key=lambda x: (x.number or 10**9, x.user_id)):\n                suffix = "  🔐 <i>первый вход</i>" if p.user_id in pending_activation else ""\n                lines.append(f"{p.number}) {player_link(p)}{suffix}")\n        else:\n            lines.append("— пока никого")\n        ready_count = max(0, len(game.players) - len(pending_activation))\n        lines += [\n            "",\n            f"👤 Всего: <b>{len(game.players)}</b> · ✅ Готовы: <b>{ready_count}</b>",\n        ]\n        if pending_activation:\n            lines.append(f"🔐 Первый вход в бота: <b>{len(pending_activation)}</b>")\n        lines += [\n            f"Минимум для старта: <b>{MODES[game.mode]['min_players']}</b>",\n            "",\n            "Нажми кнопку ниже, чтобы войти в игру.",\n        ]\n''',
    "registration pending activation UI",
)

replace_once(
    ENGINE,
    '''        message_id = game.registration_message_id or game.pinned_message_id\n        await self._safe_disable(bot, game.chat_id, message_id)\n        await self._safe_unpin(bot, game.chat_id, message_id)\n        await self._safe_delete(bot, game.chat_id, game.registration_warning_id)\n        await self._safe_delete(bot, game.chat_id, message_id)\n        game.registration_message_id = None\n''',
    '''        message_id = game.registration_message_id or game.pinned_message_id\n        await self._safe_disable(bot, game.chat_id, message_id)\n        await self._safe_unpin(bot, game.chat_id, message_id)\n        await self._safe_delete(bot, game.chat_id, game.registration_warning_id)\n        await self._safe_delete(bot, game.chat_id, message_id)\n        for prompt_id in (game.temp.get("_activation_prompt_ids") or {}).values():\n            try:\n                await self._safe_delete(bot, game.chat_id, int(prompt_id))\n            except (TypeError, ValueError):\n                pass\n        game.temp.pop("_activation_prompt_ids", None)\n        game.temp.pop("_pending_pm_activation", None)\n        game.registration_message_id = None\n''',
    "cleanup activation prompts",
)

replace_once(
    CALLBACKS,
    '''    await engine.update_registration_message(callback.bot, game)\n    pm_open = True\n    try:\n        await callback.bot.send_chat_action(user.id, "typing")\n    except Exception:\n        pm_open = False\n\n    if pm_open:\n        await callback.answer("Ты в игре!")\n        await engine._safe_pm(callback.bot, user.id, "✅ Ты зарегистрирован(а). Роль придёт сюда после старта партии.")\n    else:\n        await callback.answer(\n            "✅ Ты уже зарегистрирован(а). До старта игры открой ЛС с ботом и нажми /start — повторно жать «Присоединиться» не нужно.",\n            show_alert=True,\n        )\n''',
    '''    pm_state = await engine._probe_private_chat(callback.bot, user.id)\n    if pm_state is False:\n        pending = {\n            int(uid) for uid in (game.temp.get("_pending_pm_activation") or [])\n            if str(uid).lstrip("-").isdigit()\n        }\n        pending.add(user.id)\n        game.temp["_pending_pm_activation"] = sorted(pending)\n        await engine.persist(game)\n        await engine.update_registration_message(callback.bot, game)\n\n        username = None\n        try:\n            username = (await callback.bot.get_me()).username\n        except Exception:\n            pass\n        markup = None\n        if username:\n            payload = f"join_{game.session_id}_{game.chat_id}"\n            markup = InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(\n                text="🚀 Открыть бота → START",\n                url=f"https://t.me/{username}?start={payload}",\n            )]])\n        player = game.get_player(user.id)\n        prompt = await engine._safe_group(\n            callback.bot,\n            game.chat_id,\n            "🙂 <b>Добро пожаловать в Mafia Optimisma!</b>\\n\\n"\n            f"{player_link(player) if player else escape(user.full_name)}, твоё место уже забронировано 🔐\\n"\n            "Это первый вход. Нажми кнопку ниже, в открывшемся ЛС нажми <b>START</b> — "\n            "и место подтвердится автоматически.\\n\\n"\n            "<i>Повторно «Присоединиться» нажимать не нужно. В следующих играх этого шага уже не будет.</i>",\n            reply_markup=markup,\n        )\n        if prompt:\n            prompts = dict(game.temp.get("_activation_prompt_ids") or {})\n            prompts[str(user.id)] = prompt.message_id\n            game.temp["_activation_prompt_ids"] = prompts\n            await engine.persist(game)\n        await callback.answer(\n            "✅ Ты уже в списке. Для первой игры осталось одно касание: открой бота по кнопке и нажми START.",\n            show_alert=True,\n        )\n    else:\n        # Reachable or temporarily uncertain: registration remains valid. Only a\n        # confirmed Telegram permission error may request first-time activation.\n        pending = {\n            int(uid) for uid in (game.temp.get("_pending_pm_activation") or [])\n            if str(uid).lstrip("-").isdigit()\n        }\n        if user.id in pending:\n            pending.discard(user.id)\n            game.temp["_pending_pm_activation"] = sorted(pending)\n            await engine.persist(game)\n        await engine.update_registration_message(callback.bot, game)\n        await callback.answer("Ты в игре!")\n        if pm_state is True:\n            await engine._safe_pm(callback.bot, user.id, "✅ Ты зарегистрирован(а). Роль придёт сюда после старта партии.")\n''',
    "first-time join deep-link flow",
)

replace_once(
    PRIVATE,
    '''    await engine.storage.ensure_profile(user.id, user.full_name, user.username)\n    await message.answer(\n        "🎲 <b>Mafia Optimisma</b>\\n"\n        "Даже в мафии есть место оптимизму!\\n\\n"\n        "Команды:\\n"\n        "/menu — меню\\n"\n        "/profile — профиль\\n"\n        "/shop — магазин\\n"\n        "/roles — роли\\n\\n"\n        "Чтобы войти в игру, нажми кнопку «Присоединиться» в групповом чате."\n    )\n''',
    '''    await engine.storage.ensure_profile(user.id, user.full_name, user.username)\n\n    linked_game = None\n    args = (command.args or "").strip()\n    if args.startswith("join_"):\n        try:\n            _, session, chat_raw = args.split("_", 2)\n            candidate = store.get(int(chat_raw))\n            if (\n                candidate\n                and candidate.session_id == session\n                and candidate.phase == Phase.REGISTRATION\n                and candidate.get_player(user.id)\n            ):\n                linked_game = candidate\n        except (ValueError, AttributeError):\n            linked_game = None\n    if linked_game is None:\n        candidate = store.game_by_user(user.id)\n        if candidate and candidate.phase == Phase.REGISTRATION and candidate.get_player(user.id):\n            linked_game = candidate\n\n    if linked_game is not None:\n        async with engine.lock_for(linked_game.chat_id):\n            pending = {\n                int(uid) for uid in (linked_game.temp.get("_pending_pm_activation") or [])\n                if str(uid).lstrip("-").isdigit()\n            }\n            pending.discard(user.id)\n            linked_game.temp["_pending_pm_activation"] = sorted(pending)\n            prompts = dict(linked_game.temp.get("_activation_prompt_ids") or {})\n            prompt_id = prompts.pop(str(user.id), None)\n            linked_game.temp["_activation_prompt_ids"] = prompts\n            await engine.persist(linked_game)\n        if prompt_id:\n            try:\n                await engine._safe_delete(message.bot, linked_game.chat_id, int(prompt_id))\n            except (TypeError, ValueError):\n                pass\n        await engine.update_registration_message(message.bot, linked_game)\n        await message.answer(\n            "🙂 <b>Добро пожаловать в Mafia Optimisma!</b>\\n\\n"\n            "✅ Личный игровой канал активирован.\\n"\n            f"🎭 Твоё место в игре «{linked_game.chat_title}» закреплено.\\n\\n"\n            "Теперь просто возвращайся в группу и жди старта — повторно нажимать "\n            "«Присоединиться» не нужно. В следующих партиях достаточно одного JOIN 😎"\n        )\n        return\n\n    await message.answer(\n        "🙂 <b>Добро пожаловать в Mafia Optimisma!</b>\\n"\n        "Даже в мафии есть место оптимизму 😎\\n\\n"\n        "Личный канал готов: сюда будут приходить роли и ночные действия.\\n"\n        "Теперь найди регистрацию в игровом чате и нажми «➕ Присоединиться».\\n\\n"\n        "Команды: /menu · /profile · /shop · /roles"\n    )\n''',
    "private start onboarding",
)

print("FIRST-TIME ONBOARDING APPLIED")
