from pathlib import Path

ENGINE = Path("mafia_optimisma/engine.py")
text = ENGINE.read_text(encoding="utf-8")

old = '''    @staticmethod\n    def _seconds_text(value: int | float) -> str:\n        try:\n            number = float(value)\n        except (TypeError, ValueError):\n            return str(value)\n        if number.is_integer():\n            return str(int(number))\n        return f"{number:g}"\n\n    def _feature(self, game: GameState | None, key: str, fallback: bool) -> bool:\n'''
new = '''    @staticmethod\n    def _seconds_text(value: int | float) -> str:\n        try:\n            number = float(value)\n        except (TypeError, ValueError):\n            return str(value)\n        if number.is_integer():\n            return str(int(number))\n        return f"{number:g}"\n\n    @staticmethod\n    def _pm_permanently_unavailable(exc: Exception) -> bool:\n        # Only explicit Telegram permission/addressing errors prove that the bot\n        # cannot write to this user. A timeout/network hiccup must never eject a\n        # registered player.\n        if isinstance(exc, TelegramForbiddenError):\n            return True\n        if isinstance(exc, TelegramBadRequest):\n            message = str(exc).lower()\n            permanent_markers = (\n                "chat not found",\n                "user not found",\n                "bot was blocked",\n                "bot can't initiate conversation",\n                "bot cannot initiate conversation",\n                "user is deactivated",\n            )\n            return any(marker in message for marker in permanent_markers)\n        return False\n\n    async def _probe_private_chat(self, bot: Bot, user_id: int) -> bool | None:\n        \"\"\"Return True=reachable, False=definitely unreachable, None=temporary uncertainty.\"\"\"\n        for attempt in range(2):\n            try:\n                await bot.send_chat_action(user_id, "typing")\n                return True\n            except Exception as exc:\n                if self._pm_permanently_unavailable(exc):\n                    return False\n                self.log.warning(\n                    "Temporary PM probe failure user=%s attempt=%s: %s",\n                    user_id, attempt + 1, exc,\n                )\n                await asyncio.sleep(0)\n        return None\n\n    def _feature(self, game: GameState | None, key: str, fallback: bool) -> bool:\n'''
if new not in text:
    if old not in text:
        raise RuntimeError("helper insertion point not found")
    text = text.replace(old, new, 1)

old = '''            unreachable: list[PlayerState] = []\n            for p in game.players.values():\n                try:\n                    await bot.send_chat_action(p.user_id, "typing")\n                except Exception:\n                    unreachable.append(p)\n            if unreachable:\n                names = ", ".join(escape(p.name) for p in unreachable)\n                if not drop_unreachable:\n                    await self._safe_group(bot, game.chat_id, f"⚠️ Не могу начать: откройте ЛС с ботом и нажмите /start — {names}.")\n                    return\n\n                # A registration timeout must never hang forever because one\n                # participant never opened the bot PM. Remove only unreachable\n                # registrations and continue when enough reachable players remain.\n                for p in unreachable:\n                    game.players.pop(p.user_id, None)\n                    if store.user_to_chat.get(p.user_id) == game.chat_id:\n                        store.user_to_chat.pop(p.user_id, None)\n                await self.persist(game)\n                await self._safe_group(\n                    bot, game.chat_id,\n                    f"⚠️ Не смог отправить роль: {names}. "\n                    "Эти игроки исключены из текущей регистрации, потому что ЛС с ботом не открыты.",\n                )\n                if len(game.players) < min_players:\n                    await self.close_registration_ui(bot, game)\n                    await self._safe_group(\n                        bot, game.chat_id,\n                        f"⏳ Регистрация закрыта. После проверки ЛС осталось {len(game.players)} "\n                        f"игрока(ов), а нужно минимум {min_players}.",\n                    )\n                    await self.storage.delete_game_state(game.chat_id)\n                    store.remove_game(game.chat_id)\n                    return\n'''
new = '''            unreachable: list[PlayerState] = []\n            for p in list(game.players.values()):\n                pm_state = await self._probe_private_chat(bot, p.user_id)\n                # None means Telegram/network was temporarily inconclusive. Keep\n                # the player: only a confirmed permanent error can remove them.\n                if pm_state is False:\n                    unreachable.append(p)\n            if unreachable:\n                names = ", ".join(escape(p.name) for p in unreachable)\n                if not drop_unreachable:\n                    await self._safe_group(\n                        bot, game.chat_id,\n                        f"⚠️ Telegram пока не разрешает боту написать в ЛС: {names}. "\n                        "Если это первая игра — откройте бота один раз и нажмите /start. "\n                        "В следующих партиях повторять это не нужно.",\n                    )\n                    return\n\n                # Only definitely unreachable PMs are removed. Temporary API or\n                # Railway failures never eject a participant from registration.\n                for p in unreachable:\n                    game.players.pop(p.user_id, None)\n                    if store.user_to_chat.get(p.user_id) == game.chat_id:\n                        store.user_to_chat.pop(p.user_id, None)\n                await self.persist(game)\n                await self._safe_group(\n                    bot, game.chat_id,\n                    f"⚠️ {names}: Telegram не разрешает отправить секретную роль в ЛС. "\n                    "Бота нужно открыть один раз; после этого отдельная отметка перед играми не требуется.",\n                )\n                if len(game.players) < min_players:\n                    await self.close_registration_ui(bot, game)\n                    await self._safe_group(\n                        bot, game.chat_id,\n                        f"⏳ Регистрация закрыта. Доступны для игры {len(game.players)} "\n                        f"игрока(ов), а нужно минимум {min_players}.",\n                    )\n                    await self.storage.delete_game_state(game.chat_id)\n                    store.remove_game(game.chat_id)\n                    return\n'''
if new not in text:
    if old not in text:
        raise RuntimeError("registration PM block not found")
    text = text.replace(old, new, 1)

old = '''            await self._safe_pm(bot, p.user_id, text)\n\n    async def start_night(self, bot: Bot, game: GameState, allow_from_resolving: bool = False) -> None:\n'''
new = '''            # Role delivery is important enough to retry: a single transient\n            # Telegram/Railway error must not leave a valid participant role-less.\n            delivered = None\n            for _ in range(3):\n                delivered = await self._safe_pm(bot, p.user_id, text)\n                if delivered:\n                    break\n                await asyncio.sleep(0)\n            if not delivered:\n                self.log.error("Role delivery failed after retries user=%s chat=%s", p.user_id, game.chat_id)\n\n    async def start_night(self, bot: Bot, game: GameState, allow_from_resolving: bool = False) -> None:\n'''
if new not in text:
    if old not in text:
        raise RuntimeError("role delivery block not found")
    text = text.replace(old, new, 1)

ENGINE.write_text(text, encoding="utf-8")
print("PM REACHABILITY HOTFIX APPLIED")
